name: E2E Tests
on:
  push:
    branches:
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '16.6.0'
      # - name: Install dependencies
      #   run: yarn --frozen-lockfile
      # - name: Run e2e tests
      #   env:
      #     READING_LIST_EXTENSION_SECRET: ${{ secrets.READING_LIST_EXTENSION_SECRET }}
      #   run: yarn cypress
      - name: Create Pull Request
        uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const { repo, owner } = context.repo;
            console.log('sha', process.env.SHA);
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${process.env.SHA}`
            });
