name: E2E Tests
on:
  push:
    branches:
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '16.6.0'
      # - name: Install dependencies
      #   run: yarn --frozen-lockfile
      # - name: Run e2e tests
      #   env:
      #     READING_LIST_EXTENSION_SECRET: ${{ secrets.READING_LIST_EXTENSION_SECRET }}
      #   run: yarn cypress
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: staging
          target_branch: main
          title: My pull request
          body: '**Automated pull request**'
          reviewer: octocat
          assignee: octocat
          draft: true
          old_string: '<!-- Add your description here -->'
          new_string: '** Automatic pull request**'
          get_diff: true
          ignore_users: 'dependabot'
